export const SET_CHAT_WINDOW = "SET_CHAT_WINDOW";

export const HANDLE_USER_INPUT = "HANDLE_USER_INPUT";

export const RENDER_MESSAGE_ONCE = "RENDER_MESSAGE_ONCE";

export const HANDLE_DISABLE_INPUT = "HANDLE_DISABLE_INPUT";
